name: Notion to GitHub Sync
on:
  workflow_dispatch:  # 手動トリガー＆API呼び出し用

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug webhook payload
        run: |
          echo "=== Webhook Debug Info ==="
          echo "Event name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "=== Environment Variables ==="
          env | sort
