name: Notion to GitHub Sync
on:
  repository_dispatch:
    types: [notion-article-updated]  # カスタムイベントタイプ

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Debug payload
        run: |
          echo "Event type: ${{ github.event.action }}"
          echo "Client payload: ${{ toJson(github.event.client_payload) }}"
          
      - name: Process Notion update
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: |
          # github.event.client_payloadからNotion記事IDなどを取得
          echo "Processing article: ${{ github.event.client_payload.page_id }}"
